export const ALL_BC_REQUEST = "ALL_BC_REQUEST";
export const ALL_BC_SUCCESS = "ALL_BC_SUCCESS";
export const ALL_BC_FAIL = "ALL_BC_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"


export const NEW_BC_REQUEST = "NEW_BC_REQUEST"
export const NEW_BC_SUCCESS = "NEW_BC_SUCCESS"
export const NEW_BC_FAIL = "NEW_BC_FAIL"
export const NEW_BC_RESET = "NEW_BC_RESET"

export const DELETE_BC_REQUEST = "DELETE_BC_REQUEST"
export const DELETE_BC_SUCCESS = "DELETE_BC_SUCCESS"
export const DELETE_BC_FAIL = "DELETE_BC_FAIL"
export const DELETE_BC_RESET = "DELETE_BC_RESET"


export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET"

export const DETAILS_PRODUCT_REQUEST = "DETAILS_PRODUCT_REQUEST"
export const DETAILS_PRODUCT_SUCCESS = "DETAILS_PRODUCT_SUCCESS"
export const DETAILS_PRODUCT_FAIL = "DETAILS_PRODUCT_FAIL"
export const DETAILS_PRODUCT_RESET = "DETAILS_PRODUCT_RESET"







export const CLEAR_ERRORS = "CLEAR_ERRORS"

