export const ALL_BRAND_REQUEST = "ALL_BRAND_REQUEST";
export const ALL_BRAND_SUCCESS = "ALL_BRAND_SUCCESS";
export const ALL_BRAND_FAIL = "ALL_BRAND_FAIL";

export const BLOG_DETAILS_REQUEST = "BLOG_DETAILS_REQUEST"
export const BLOG_DETAILS_SUCCESS = "BLOG_DETAILS_SUCCESS"
export const BLOG_DETAILS_FAIL = "BLOG_DETAILS_FAIL"

export const NEW_BRAND_REQUEST = "NEW_BRAND_REQUEST"
export const NEW_BRAND_SUCCESS = "NEW_BRAND_SUCCESS"
export const NEW_BRAND_FAIL = "NEW_BRAND_FAIL"
export const NEW_BRAND_RESET = "NEW_BRAND_RESET"


export const DELETE_BRAND_REQUEST = "DELETE_BRAND_REQUEST"
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS"
export const DELETE_BRAND_FAIL = "DELETE_BRAND_FAIL"
export const DELETE_BRAND_RESET = "DELETE_BRAND_RESET"


export const UPDATE_BRAND_REQUEST = "UPDATE_BRAND_REQUEST"
export const UPDATE_BRAND_SUCCESS = "UPDATE_BRAND_SUCCESS"
export const UPDATE_BRAND_FAIL = "UPDATE_BRAND_FAIL"
export const UPDATE_BRAND_RESET = "UPDATE_BRAND_RESET"

export const DETAILS_BLOG_REQUEST = "DETAILS_BLOG_REQUEST"
export const DETAILS_BLOG_SUCCESS = "DETAILS_BLOG_SUCCESS"
export const DETAILS_BLOG_FAIL = "DETAILS_BLOG_FAIL"
export const DETAILS_BLOG_RESET = "DETAILS_BLOG_RESET"







export const CLEAR_ERRORS = "CLEAR_ERRORS"

