export const ALL_PC_REQUEST = "ALL_PC_REQUEST";
export const ALL_PC_SUCCESS = "ALL_PC_SUCCESS";
export const ALL_PC_FAIL = "ALL_PC_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"


export const NEW_PC_REQUEST = "NEW_PC_REQUEST"
export const NEW_PC_SUCCESS = "NEW_PC_SUCCESS"
export const NEW_PC_FAIL = "NEW_PC_FAIL"
export const NEW_PC_RESET = "NEW_PC_RESET"




export const DELETE_PC_REQUEST = "DELETE_PC_REQUEST"
export const DELETE_PC_SUCCESS = "DELETE_PC_SUCCESS"
export const DELETE_PC_FAIL = "DELETE_PC_FAIL"
export const DELETE_PC_RESET = "DELETE_PC_RESET"


export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET"

export const DETAILS_PRODUCT_REQUEST = "DETAILS_PRODUCT_REQUEST"
export const DETAILS_PRODUCT_SUCCESS = "DETAILS_PRODUCT_SUCCESS"
export const DETAILS_PRODUCT_FAIL = "DETAILS_PRODUCT_FAIL"
export const DETAILS_PRODUCT_RESET = "DETAILS_PRODUCT_RESET"







export const CLEAR_ERRORS = "CLEAR_ERRORS"

